// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Seller.Persistence;

namespace Seller.Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200101100136_SeedVehicles")]
    partial class SeedVehicles
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("Seller.Domain.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Registration")
                        .HasColumnType("TEXT");

                    b.Property<string>("VIN")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Registration = "Registration1",
                            VIN = "VIN1VIN1VIN1VIN1"
                        },
                        new
                        {
                            Id = 2,
                            Registration = "Registration2",
                            VIN = "VIN2VIN2VIN2VIN2"
                        },
                        new
                        {
                            Id = 3,
                            Registration = "Registration3",
                            VIN = "VIN3VIN3VIN3VIN3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
